name: AutoRun
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run
        run: |
          pip install requests
          python scraper.py
      - name: Push
        run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@github.com"
          git add .
          git commit -m "update" || exit 0
          git push
